core/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('visualizer/', include('visualizer.urls')),
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home')
]

visualizer/urls.py
from django.urls import path
from . import views

app_name = 'visualizer'
urlpatterns = [
    path('', views.index, name='index'),
    path('classroom-registration/', views.classroom_registration, name='classroom-registration'),
    path('<int:classroom_id>/', views.classroom_overview, name='classroom'),
    path('<int:classroom_id>/<int:student_id>/grades/', views.grades, name='grades'),
    path('<int:classroom_id>/<int:student_id>/student-update', views.student_update, name='student-update'),
    path('<int:classroom_id>/<int:student_id>/student-delete', views.student_delete, name='student-delete'),
    path('<int:classroom_id>/classroom-update', views.classroom_update, name='classroom-update'),
    path('<int:classroom_id>/classroom-delete', views.classroom_delete, name='classroom-delete'),
    path('<int:classroom_id>/<int:student_id>/chart/', views.charts, name='charts'),
    path('<int:student_id>/grades-chart/', views.grades_chart, name='grades-chart'),

]

visualizer/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Classroom(models.Model):
    classroom_name = models.CharField(max_length=200)
    grade = models.CharField(max_length=40)
    teachers = models.CharField(max_length=100)

    def __str__(self):
        return self.classroom_name + '(' + self.grade + ')'

class Student(models.Model):
    student_name = models.CharField(max_length=200)
    classroom_name = models.ForeignKey(Classroom, on_delete=models.CASCADE)

    def __str__(self):
        return self.student_name

class Grades(models.Model):
    student_name = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='student_grades')
    classroom_name = models.ForeignKey(Classroom, on_delete=models.CASCADE, related_name='classroom_grades')

    class Subjects(models.TextChoices):
        sight_words = "Sight Words"
        reading = "Reading"
        math = "Math"
        writing = "Writing"
        phonics = "Phonics"

    subject = models.CharField(
        max_length=12,
        choices=Subjects.choices,
        default=Subjects.reading,
        )

    date = models.DateField()

    grades = models.PositiveIntegerField(default=50, validators=[MinValueValidator(0), MaxValueValidator(100)])

visualizer/forms.py
from django import forms
from visualizer.models import Classroom, Student, Grades

class ClassroomInformationForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = '__all__'

class StudentInformationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

class GradesInformationForm(forms.ModelForm):
    class Meta:
        model = Grades
        fields = '__all__'

core/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'core/home.html')

visualizer/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.http import JsonResponse
from .models import Classroom, Student, Grades
from .forms import ClassroomInformationForm, StudentInformationForm, GradesInformationForm
from django.urls import reverse

def home_view(request, *args, **kwargs):
    return render(request, 'visualizer/home.html')

def index(request):
    classroom_list = Classroom.objects.order_by('grade')
    context = {
        'classroom_list': classroom_list
    }
    return render(request, 'visualizer/index.html', context)

def classroom_registration(request):
    if request.method == 'POST':
        form = ClassroomInformationForm(request.POST)

        if form.is_valid():
            classroom = form.save()
            return redirect(reverse('visualizer:classroom', args=(classroom.id,)))
    else:
        form = ClassroomInformationForm()

    return render(request, 'visualizer/classroom_registration.html', {'form': form})

def classroom_update(request, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)

    if request.method == 'POST':
        form = ClassroomInformationForm(request.POST, instance=classroom)
        if form.is_valid():
            form.save()
            return redirect('visualizer:classroom', classroom.id)

    else:
        form = ClassroomInformationForm(instance=classroom)

    return render(request, 'visualizer/classroom_update.html',
                  {'classroom': classroom, 'form': form})

def student_update(request, classroom_id, student_id):
    student = Student.objects.get(id=student_id)

    if request.method == 'POST':
        form = StudentInformationForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('visualizer:classroom', classroom_id)

    else:
        form = StudentInformationForm(instance=student)

    return render(request, 'visualizer/student_update.html',
                  {'form': form})


def classroom_overview(request, classroom_id):
    if request.method == 'POST':
        form = StudentInformationForm(request.POST, )

        if form.is_valid():
            student = form.save()
            student_class = Student.objects.filter(classroom_name=classroom_id)
            return render(request, 'visualizer/classroom_overview.html',
                          {'student_class': student_class, 'form': form})
    else:
        form = StudentInformationForm()

        try:
            student_class = Student.objects.filter(classroom_name=classroom_id)

        except Student.DoesNotExist:
            return render(request, 'visualizer/classroom_overview.html',
                          {'form': form})

    return render(request, 'visualizer/classroom_overview.html',
                  {'student_class': student_class, 'form': form})

def classroom_delete(request, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)
    if request.method == 'POST':
        classroom.delete()
        return redirect('visualizer:index')

    return render(request, 'visualizer/classroom_delete.html',
                  {'classroom': classroom})

def student_delete(request, classroom_id, student_id):
    student = Student.objects.get(id=student_id)

    if request.method == 'POST':
        student.delete()
        return redirect('visualizer:classroom', classroom_id)

    return render(request, 'visualizer/student_delete.html',
                  {'student': student})

def grades(request, classroom_id, student_id):
    grades = Grades.objects.filter(student_name=student_id)
    if request.method == 'POST':

        form = GradesInformationForm(request.POST)

        if form.is_valid():
            grades = form.save()
            return redirect('visualizer:grades', classroom_id, student_id)
    else:
        form = GradesInformationForm()

    return render(request, 'visualizer/student_performance.html',
                  {'grades': grades, 'form': form, 'classroom': classroom_id, 'student': student_id})


def charts(request, classroom_id, student_id):
    student = Student.objects.get(pk=student_id)
    return render(request, 'visualizer/charts.html', {'student': student})


def grades_chart(request, student_id):
    labels = []
    data = []

    queryset = Grades.objects.filter(student_name=student_id)
    for subject in queryset:
        labels.append(subject.subject)
        data.append(subject.grades)

    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

visualizer/templates/core/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Student Visualizer</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="main">
      <div class="banner">
        <h1>Visualizer</h1>
      </div>
      <div class="info">
        <div class="links">
          <div class="link">
            <p><a href="{% url 'visualizer:index' %}">View Classrooms</a></p>
          </div>
          <div class="link">
            <p><a href="{% url 'visualizer:classroom-registration' %}">Create Classroom</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <div class="left">
        <div class="small-link">
          <p class="footer-p">about</p>
        </div>
        <div class="small-link">
          <p class="footer-p">contact us</p>
        </div>
      </div>
      <div class="right">
        <div class="small-img">
          <p class="footer-p">img</p>
        </div>
        <div class="small-img">
          <p class="footer-p">img</p>
        </div>
        <div class="small-img">
          <p class="footer-p">img</p>
        </div>
      </div>
    </div>
  </body>
</html>

visualizer/templates/visualizer/charts.html
{% block content %}
  <div id="container" style="width: 75%;">
    <canvas id="grades-chart" data-url="{% url 'visualizer:grades-chart' student.id%}"></canvas>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $gradesChart = $("#grades-chart");

      $.ajax({
        url: $gradesChart.data("url"),
        success: function (data) {

          var ctx = $gradesChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Grades',
                backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 159, 64, 0.2)',
                  'rgba(255, 205, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                ],
                borderColor: [
                  'rgb(255, 99, 132)',
                  'rgb(255, 159, 64)',
                  'rgb(255, 205, 86)',
                  'rgb(75, 192, 192)',
                  'rgb(54, 162, 235)',
                ],
                borderWidth: 1,
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Grades Bar Chart'
              }
            }
          });
          console.log(data)

        }
      });

    });

  </script>

{% endblock %}

visualizer/templates/visualizer/class_overview.html
<!DOCTYPE html>
<html>
  <h1>{{ students.student_class }}</h1>
  <ul>
    {% for student in student.student_name.all %}
      <li>{{ student }}</li>
    {% endfor %}
  </ul>
</html>

visualizer/templates/visualizer/class_registration.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Register Classroom</title>
  </head>

  <body>
    <h1>Create a Classroom</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

visualizer/templates/visualizer/classroom_delete.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Delete Classroom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1> Delete Classroom </h1>
    <p> Are you sure you want to delete this classroom: {{ classroom.classroom_name }}</p>

    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Delete">
    </form>
  </body>
</html>

visualizer/templates/visualizer/classroom_overview.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Classroom Overview</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    {% if student_class %}
    <h1>Students in Classroom</h1>
    <ul>
      {% for student in student_class %}
        <li><a href="{% url 'visualizer:grades' student.classroom_name.id student.id%}">{{ student }}</a>
        - <a href="{% url 'visualizer:student-update' student.classroom_name.id student.id %}">[edit]</a></li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No students have been entered into the class</p>
    {% endif %}

    <h1>Add a Student to Your Classroom</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

visualizer/templates/visualizer/classroom_registration.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Register Classroom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Create a Classroom</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

visualizer/templates/visualizer/classroom_update.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Update Classroom</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Update Classroom</h1>

    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
    <ul>
      <li>
        <a href="{% url 'visualizer:classroom-delete' classroom.id %}">[delete classroom]</a>
      </li>
    </ul>
  </body>
</html>

visualizer/templates/visualizer/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Student Visualizer</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="form-div">
      {% if classroom_list %}
        <ul>
          {% for classroom in classroom_list %}
            <li><a href="{% url 'visualizer:classroom' classroom.id%}">{{ classroom.grade}} {{ classroom.classroom_name }}</a>
               - <a href="{% url 'visualizer:classroom-update' classroom.id %}">[edit]</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No classes have been created</p>
      {% endif %}
    </div>

    <p><a href="{% url 'visualizer:classroom-registration' %}">Create a new classroom</a></p>
  </body>

</html>

visualizer/templates/visualizer/student_delete.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Remove Student</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1> Delete Student </h1>
    <p> Are you sure you want to delete this student: {{ student.student_name }}</p>

    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Delete">
    </form>
  </body>
</html>

visualizer/templates/visualizer/student_performance.html
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>Student Performance</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    {% if grades %}
      <h1> Student Grades</h1>
    <ul>
      {% for grade in grades %}
        <li>{{ grade.subject }} {{ grade.grades }} - [{{ grade.date }}]</li>
        {% endfor %}
    </ul>
    <a href="{% url 'visualizer:charts' classroom student %}">Chart it!</a>

    {% else %}
      <p>Student does not yet have any grades</p>
    {% endif %}
    <h1>Record Grades for your Student!</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
  </body>


</html>

visualizer/templates/visualizer/student_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Update Student</title>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@400;500;600;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <h1>Update Student Information</h1>

    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
  </body>
</html>